repos:
  - repo: https://github.com/psf/black
    rev: 24.3b0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.0
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 6.2.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear==23.11.24]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
